### ISSUE TITLE
Hookcard has unhandled promise

### ISSUE THREAD

**Issue by marcobuettner** [maxrumsey/hookcord#6]
We have found at a long term run often this warning in our log.

> (node:17200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:17200) UnhandledPromiseRejectionWarning: Error: Ratelimit Reached.
    at Object.handleRatelimit (/home/scidev2/Bots/hltv-scorebot/node_modules/hookcord/src/util.js:9:11)
    at Base.send (/home/scidev2/Bots/hltv-scorebot/node_modules/hookcord/src/base.js:110:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:17200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

**Comment by maxrumsey** [comment]
I am looking into this. :) Could you send me the code used to construct the base class? In specific any options you pass into the constructor.

**Comment by marcobuettner** [comment]
```javascript
var hookcord = require('hookcord');
var Base = hookcord.Base;
var json = {
		'username': hook_name,
		'embeds': [{
			'title':       title,
			'description': message
		}]
	};
})

Webhook = new Base(hook_id + "/" + hook_secret, {}, json);
Webhook.send();
```

**Comment by maxrumsey** [comment]
It appears that the reason these warnings are being outputted in console is because your application is hitting Discord's Ratelimits and an error is being thrown. These warnings should be caught and handled with a `.catch()` function like the one below:
```javascript
Webhook = new Base(hook_id + "/" + hook_secret, {}, json);
Webhook.send()
	.catch(function(err) {
		console.log('Ratelimits are being hit! Slow down!');
	});
```

If you would not like an error to be thrown you can look at other Ratelimit handling options at [Hookcord's API](https://maxrumsey.xyz/hookcord/?api#WebhookOptions). You can learn more about promises [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).

**Comment by marcobuettner** [comment]
Thanks for the reply. I will update the code. :)
